
package uaic.webnpchunkerro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NpChunkerRoWS", targetNamespace = "http://webNpChunkerRo.uaic/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NpChunkerRoWS {


    /**
     * 
     * @param taggedXml
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "chunkTaggedText", targetNamespace = "http://webNpChunkerRo.uaic/", className = "uaic.webnpchunkerro.ChunkTaggedText")
    @ResponseWrapper(localName = "chunkTaggedTextResponse", targetNamespace = "http://webNpChunkerRo.uaic/", className = "uaic.webnpchunkerro.ChunkTaggedTextResponse")
    @Action(input = "http://webNpChunkerRo.uaic/NpChunkerRoWS/chunkTaggedTextRequest", output = "http://webNpChunkerRo.uaic/NpChunkerRoWS/chunkTaggedTextResponse")
    public String chunkTaggedText(
        @WebParam(name = "taggedXml", targetNamespace = "")
        String taggedXml);

    /**
     * 
     * @param inputText
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "chunkText", targetNamespace = "http://webNpChunkerRo.uaic/", className = "uaic.webnpchunkerro.ChunkText")
    @ResponseWrapper(localName = "chunkTextResponse", targetNamespace = "http://webNpChunkerRo.uaic/", className = "uaic.webnpchunkerro.ChunkTextResponse")
    @Action(input = "http://webNpChunkerRo.uaic/NpChunkerRoWS/chunkTextRequest", output = "http://webNpChunkerRo.uaic/NpChunkerRoWS/chunkTextResponse")

    public String chunkText(@WebParam(name = "inputText", targetNamespace = "") String inputText);

}
