
package uaic.webnpchunkerro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NpChunkerRoWS", targetNamespace = "http://webNpChunkerRo.uaic/", wsdlLocation = "http://nlptools.info.uaic.ro/WebNpChunkerRo/NpChunkerRoWS?wsdl")
public class NpChunkerRoWS_Service
    extends Service
{

    private final static URL NPCHUNKERROWS_WSDL_LOCATION;
    private final static WebServiceException NPCHUNKERROWS_EXCEPTION;
    private final static QName NPCHUNKERROWS_QNAME = new QName("http://webNpChunkerRo.uaic/", "NpChunkerRoWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://nlptools.info.uaic.ro/WebNpChunkerRo/NpChunkerRoWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NPCHUNKERROWS_WSDL_LOCATION = url;
        NPCHUNKERROWS_EXCEPTION = e;
    }

    public NpChunkerRoWS_Service() {
        super(__getWsdlLocation(), NPCHUNKERROWS_QNAME);
    }

    public NpChunkerRoWS_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), NPCHUNKERROWS_QNAME, features);
    }

    public NpChunkerRoWS_Service(URL wsdlLocation) {
        super(wsdlLocation, NPCHUNKERROWS_QNAME);
    }

    public NpChunkerRoWS_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NPCHUNKERROWS_QNAME, features);
    }

    public NpChunkerRoWS_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NpChunkerRoWS_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NpChunkerRoWS
     */
    @WebEndpoint(name = "NpChunkerRoWSPort")
    public NpChunkerRoWS getNpChunkerRoWSPort() {
        return super.getPort(new QName("http://webNpChunkerRo.uaic/", "NpChunkerRoWSPort"), NpChunkerRoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NpChunkerRoWS
     */
    @WebEndpoint(name = "NpChunkerRoWSPort")
    public NpChunkerRoWS getNpChunkerRoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webNpChunkerRo.uaic/", "NpChunkerRoWSPort"), NpChunkerRoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NPCHUNKERROWS_EXCEPTION!= null) {
            throw NPCHUNKERROWS_EXCEPTION;
        }
        return NPCHUNKERROWS_WSDL_LOCATION;
    }

}
